### PR TITLE
Remove dependence on VBScript

### LINKED ISSUE #7: Maximum path character limit bug
It is not possible to open a file or directory for a path that exceeds 259 characters in length. This is specifically a limitation of explorer.exe not accepting longer paths. This wouldn't normally be an issue on Windows machines with the default `MAX_PATH` limit unchanged (as it would normally inhibit the existence of such long paths), but it is very common for network paths to exceed this.

Edit: Turns out this is a double issue. `WScript.Shell .Run` also imposes a character length limit of its own.

The first issue can be overcome by using ` (New-Object -ComObject Scripting.FileSystemObject).GetFile('some-long-file-path-here').ShortPath`. And in the case of network drives, `'\\?\UNC'` needs to be prepended to the path.

### PR DESCRIPTION
**Pull request by alexcodito**
This PR does the following:

- Removes dependence on VBScript (as MS confirmed that it will be deprecated in future Windows updates) by replacing it with `conhost.exe --headless` to retain the same behavior
- Fixes issue with paths containing certain unicode characters.

### CODE REVIEW

**Comment by Luffier** [comment]
On my system (W11, network drive) ladderr-open and ladderr-select don't seem to work 95% of the time. With files, ladderr-open works as expected. I would provide examples, but it happens with practically every torrent. 

I saw the caveat about network drives in #7, if this is the problem, could you add how to fix it in the README.

**Comment by alexcodito** [comment]
@Luffier - just to be clear, when you say 95% of the time, do you specifically mean with the latest changes of this PR (i.e. v0.6)? Or do you instead mean with v0.5?

**Comment by Luffier** [comment]
@alexcodito Yes, this PR version (v0.6).

**Comment by alexcodito** [comment]
@Luffier could you do me a favor and try the following .reg please? It essentially just prepends `\\?\UNC` to the path. It's odd because it works both with and without it. Worst case scenario, would you be willing to share a sample b64 generated URI for further investigation?

```
Windows Registry Editor Version 5.00


[HKEY_CLASSES_ROOT\ladderr-open]
@="URL:ladderr Open Protocol"
"URL Protocol"=""

[HKEY_CLASSES_ROOT\ladderr-open\shell]

[HKEY_CLASSES_ROOT\ladderr-open\shell\open]

[HKEY_CLASSES_ROOT\ladderr-open\shell\open\command]
@="conhost.exe --headless powershell -WindowStyle Hidden -Command $url = '%1' -replace 'ladderr-open:', ''; Start-Process explorer.exe ((New-Object -ComObject Scripting.FileSystemObject).GetFile(\\?\UNC' + [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($url))).ShortPath)"
[HKEY_CLASSES_ROOT\ladderr-select]
@="URL:ladderr Open Protocol"
"URL Protocol"=""

[HKEY_CLASSES_ROOT\ladderr-select\shell]

[HKEY_CLASSES_ROOT\ladderr-select\shell\open]

[HKEY_CLASSES_ROOT\ladderr-select\shell\open\command]
@="conhost.exe --headless powershell -WindowStyle Hidden -Command $url = '%1' -replace 'ladderr-select:', ''; Start-Process explorer.exe ('/select,' + (New-Object -ComObject Scripting.FileSystemObject).GetFile('\\?\UNC' + [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($url))).ShortPath)"
```

**Comment by Luffier** [comment]
Same thing.

```
// WORK
[Ladderr] Remote path:  Z:\downloads\movies\steamboat-willie-mickey
[Ladderr] URI created:  ladderr-open:WjpcZG93bmxvYWRzXG1vdmllc1xzdGVhbWJvYXQtd2lsbGllLW1pY2tleQ==
[Ladderr] Remote path:  Z:\downloads\movies\steamboat-willie-mickey
[Ladderr] URI created:  ladderr-select:WjpcZG93bmxvYWRzXG1vdmllc1xzdGVhbWJvYXQtd2lsbGllLW1pY2tleQ==
// DON'T WORK
[Ladderr] Remote path:  Z:\downloads\movies\steamboat-willie-mickey\01 - Steamboat Willie.mkv
[Ladderr] URI created:  ladderr-open:WjpcZG93bmxvYWRzXG1vdmllc1xzdGVhbWJvYXQtd2lsbGllLW1pY2tleVwwMSAtIFN0ZWFtYm9hdCBXaWxsaWUubWt2
[Ladderr] Remote path:  Z:\downloads\movies\steamboat-willie-mickey\01 - Steamboat Willie.mkv
[Ladderr] URI created:  ladderr-select:WjpcZG93bmxvYWRzXG1vdmllc1xzdGVhbWJvYXQtd2lsbGllLW1pY2tleVwwMSAtIFN0ZWFtYm9hdCBXaWxsaWUubWt2
```

**Comment by alexcodito** [comment]
Thanks for the examples. It seems that the main difference is that you're pointing to `Z:\` drive, whereas I'm pointing to `\\my-net-drive\`. I've taken the time to recreate your environment (same drive, folder structure and files as your example) and reproduced the issue. Interestingly though, I'm finding the exact opposite (WORK and DON'T WORK is the other way around for me). Did you maybe mislabel them by any chance? In any case, I'll try to get it working for both setups.

**Comment by Luffier** [comment]
No, it's not mislabeled (checked again just in case), any action over a folder seems to fail. And sorry, should have linked the torrent with the original examples: https://archive.org/details/steamboat-willie-mickey

**Comment by Luffier** [comment]
Hi, I've encountered a problem with some paths containing Japanese chars, using `conhost` fixes it. Would it be possible to split this pull request into two? One for the removal of the VB dependency and another for the path length limitation.

**Comment by alexcodito** [comment]
@Luffier that's done now. Please review/test. I'll raise another PR for the path length issue when this is merged.

**Review by Luffier — APPROVED** [review]

**Pull request merged**
