### PR TITLE
Fix max path length issue

### LINKED ISSUE #7: Maximum path character limit bug
It is not possible to open a file or directory for a path that exceeds 259 characters in length. This is specifically a limitation of explorer.exe not accepting longer paths. This wouldn't normally be an issue on Windows machines with the default `MAX_PATH` limit unchanged (as it would normally inhibit the existence of such long paths), but it is very common for network paths to exceed this.

Edit: Turns out this is a double issue. `WScript.Shell .Run` also imposes a character length limit of its own.

The first issue can be overcome by using ` (New-Object -ComObject Scripting.FileSystemObject).GetFile('some-long-file-path-here').ShortPath`. And in the case of network drives, `'\\?\UNC'` needs to be prepended to the path.

### PR DESCRIPTION
**Pull request by alexcodito**
- Fixes #7 - a Windows `explorer.exe` limitation with paths that are longer than 259 characters. 

The fix involves obtaining the "Short Path" (aka the [8.3 form](https://en.wikipedia.org/wiki/8.3_filename)) equivalent of the supplied path, e.g.:
> \\MyNetworkDrive\Downloads\Public\Some-Extremely-Long-Path-Some-Extremely-Long-Path-Some-Extremely-Long-Path-Some-Extremely-Long-Path\Some-Extremely-Long-Path-Some-Extremely-Long-Path-Some-Extremely-Long-Path.txt

Becomes:
> \\MyNetworkDrive\downloads\Public\SLVHNR\~S\SCXL2T\~U.TXT

Similarly, the following path:
> "Z:\downloads\movies\steamboat-willie-mickey\01 - Steamboat Willie.mkv"

Becomes:
> Z:\DCUKUI\~W\movies\SF2LO9\~3\03BEUL\~7.MKV

### CODE REVIEW

**Comment by Luffier** [comment]
I don't know what changed but know I can use `open` and `select` on files, but cannot do the same with folders. When testing the commands on the terminal I was getting `OperationStopped: 0x800A0035 (CTL_E_FILENOTFOUND)`, and after looking the docs, it seems that there's another function for folders: [`GetFolder`](https://learn.microsoft.com/es-es/office/vba/language/reference/user-interface-help/filesystemobject-object).

Also, the use of `Trim()` would revert the fix for paths with commas.

**Comment by alexcodito** [comment]
Thanks for testing this. Trim is the only thing that changed from last time and is what got it working for the Z:\ path (GetFile doesn't accept quoted strings, and UTF8 GetString returns strings surrounded in quotes). 

I meant to add GetFolder but forgot as it's been a few weeks since I last looked at it. There's going to be a need for an additional check now to see if it's a folder or a file and use the corresponding method. The script is getting annoyingly long and out of hand. Seriously tempted to convert this into a C# console app instead.

**Comment by alexcodito** [comment]
@Luffier I've applied a fix that I believe now works in every scenario:
- Paths longer than 259 characters
- Unicode characters (Japanese, Chinese, Russian)
- Paths with spaces
- Commas in folders, commas in file names
- Deeply nested directories
- Paths starting with \\ or Z:\

Please review and let me know if you find any further issues.

**Comment by Luffier** [comment]
@alexcodito For me, it wasn't working with filenames containing commas (at least with the example from the original [issue](https://github.com/Luffier/ladderr/issues/10). Adding the quotes in the step previous to calling `explorer.exe` works. And I see you activated the option to allow edits, so I will push a commit with the fix and merge 🚀.

**Comment by alexcodito** [comment]
Odd. For me, your latest changes completely break all functionality. I'm going to stick to using the version in my fork.

**Comment by Luffier** [comment]
Did you update the script as well? I removed the quotes in the scripts and the trim in the .reg so if you only update the .reg it would break in all cases.

**Comment by alexcodito** [comment]
I updated the script but hadn't refreshed the page. Looks it still works for all scenarios like for me (same as when using `Trim()`), so either way is fine for me. Still strange that I couldn't reproduce the issue with the commas. Oh well. Glad it's sorted now.

**Pull request merged**
